name=OptaPartitionCheck
version=0.1.0
author=Joseph Carr
maintainer=Joseph Carr
sentence=LittleFS partition check for the Opta.
paragraph=Ensures that the Opta flash storage has the 4 partitions set up in QSPIFormat. This protects the firmware capabilities that are shipped with the Opta from being overwritten by user data. The four partitions are Wifi firmware and certificates, OTA, the Provisioning KVStore, and User Data.
category=Data Storage
url=
architectures=*
includes=OptaPartitionCheck.h